author: InfluxData
author_url: https://www.influxdata.com
github_url: https://github.com/bonitoo-io/influxdb-client-swift
module: influxdb_client_swift
swift_build_tool: spm
theme: fullwidth
clean: true

custom_categories:
  - name: Client
    children:
      - InfluxDBClient
      - WriteAPI
      - QueryAPI
      - Query
      - Dialect

  - name: APIs
    children:
      - InfluxDB2API

  - name: APIs / Models
    children:
      - AddResourceMemberRequestBody
      - Authorization
      - AuthorizationAllOfLinks
      - Authorizations
      - AuthorizationUpdateRequest
      - Bucket
      - BucketLinks
      - Buckets
      - DBRP
      - DBRPUpdate
      - DBRPs
      - HealthCheck
      - IsOnboarding
      - Label
      - LabelCreateRequest
      - LabelMapping
      - LabelResponse
      - LabelUpdate
      - LabelsResponse
      - Links
      - LogEvent
      - Logs
      - OnboardingRequest
      - OnboardingResponse
      - Organization
      - Organizations
      - OrganizationLinks
      - PasswordResetBody
      - Permission
      - PostBucketRequest
      - Ready
      - Resource
      - ResourceMember
      - ResourceMembers
      - ResourceOwner
      - ResourceOwners
      - RetentionRule
      - Run
      - RunLinks
      - RunLog
      - RunManually
      - Runs
      - ScraperTargetRequest
      - ScraperTargetResponse
      - ScraperTargetResponseAllOfLinks
      - ScraperTargetResponses
      - SecretKeysResponse
      - SecretKeysResponseAllOfLinks
      - SecretKeys
      - Source
      - SourceLinks
      - Sources
      - Task
      - TaskCreateRequest
      - TaskLinks
      - TaskUpdateRequest
      - TaskStatusType
      - Tasks
      - User
      - Users
      - UserLinks
      - UsersLinks
      - Variable
      - VariableLinks
      - VariableProperties
      - Variables

  - name: Supporting Files
    children:
      - AnyCursor
      - APIHelper
      - CodableHelper
      - Cursor
      - DecodableRequestBuilderError
      - DownloadException
      - HTTPMethod
      - JSONDataEncoding
      - JSONEncodingHelper
      - KeyedDecodingContainerProtocol
      - KeyedEncodingContainerProtocol
      - OpenISO8601DateFormatter
      - ParameterEncoding
      - Response
      - String